import streamlit as st
import pandas as pd
import plotly.express as px
from datetime import datetime

# ==========================================
# 0. Page Configuration & Custom CSS (UI Upgrade)
# ==========================================
st.set_page_config(page_title="SME Tax Calculator Pro", layout="wide", page_icon="💎")

st.markdown("""
    <style>
    .stApp { background: #f8fafc; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; }
    div[data-testid="stVerticalBlock"] > div {
        background-color: #ffffff; border-radius: 16px; padding: 24px;
        box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
        border: 1px solid #e2e8f0; margin-bottom: 20px;
    }
    [data-testid="stSidebar"] { background-color: #ffffff !important; border-right: 1px solid #e2e8f0; }
    .premium-badge {
        background: linear-gradient(135deg, #fbbf24 0%, #f59e0b 100%);
        padding: 10px; border-radius: 12px; color: white; text-align: center; 
        font-weight: 700; margin-bottom: 20px; letter-spacing: 0.5px;
    }
    .stButton > button {
        background: #2563eb !important; color: white !important; border-radius: 8px !important;
        font-weight: 600; padding: 0.5rem 1rem; transition: 0.2s;
    }
    .stButton > button:hover { background: #1d4ed8 !important; transform: translateY(-1px); }
    .advice-box { background-color: #eff6ff; border-left: 4px solid #3b82f6; padding: 15px; border-radius: 4px; margin-bottom: 10px;}
    </style>
    """, unsafe_allow_html=True)

# ==========================================
# 1. Core Functions (المنطق والذكاء الاصطناعي)
# ==========================================
def authenticate_user(username, password):
    u, p = username.strip().lower(), password.strip()
    if u == "free_admin" and p == "free_admin": return True, "free"
    elif u == "premium_admin" and p == "premium_admin": return True, "premium"
    return False, None

def calculate_egyptian_taxes(revenue, expenses):
    net_profit = revenue - expenses
    # Law 152 Brackets
    if revenue < 250000: tax_152 = 1000.0
    elif revenue < 500000: tax_152 = 2500.0
    elif revenue < 1000000: tax_152 = 5000.0
    elif revenue < 2000000: tax_152 = revenue * 0.005
    elif revenue < 3000000: tax_152 = revenue * 0.0075
    else: tax_152 = revenue * 0.01
    # Law 91
    tax_91 = max(0.0, net_profit * 0.225)
    return tax_152, tax_91, net_profit

def generate_tax_advice(revenue, expenses, tax_152, tax_91):
    """محرك الذكاء الضريبي لتقديم نصائح استراتيجية للمستخدم"""
    advice = []
    if revenue == 0:
        return ["💡 سجل مبيعاتك أولاً لنتمكن من تحليل موقفك الضريبي."]
        
    # 1. Optimization: أيهما أفضل؟
    if tax_152 < tax_91:
        advice.append("💡 **التحسين الضريبي:** قانون 152 (المشروعات الصغيرة) يوفر لك مبالغ أكبر. تأكد من استخراج شهادة تصنيف من جهاز تنمية المشروعات للاستفادة من هذا القانون.")
    elif tax_91 < tax_152:
        advice.append("💡 **التحسين الضريبي:** قانون 91 (الدخل العام) أفضل لك حالياً بسبب ارتفاع مصروفاتك التشغيلية. تأكد من الاحتفاظ بجميع الفواتير الإلكترونية لخصم المصروفات قانونياً.")
    
    # 2. Scenarios: التنبيه باقتراب الشريحة
    if 240000 <= revenue < 250000:
        advice.append("⚠️ **تنبيه الشريحة:** إيراداتك تقترب جداً من 250 ألف جنيه. تجاوز هذا الرقم سينقلك للشريحة الضريبية الأعلى (2500 جنيه بدلاً من 1000 جنيه).")
    elif 950000 <= revenue < 1000000:
        advice.append("⚠️ **تنبيه الشريحة:** أنت تقترب من حاجز المليون جنيه، حيث ستتغير المحاسبة من 'مبلغ مقطوع' إلى 'نسبة مئوية' (0.5%).")
        
    return advice

def generate_html_report(revenue, expenses, tax_152, tax_91):
    """توليد تقرير HTML يمكن طباعته كـ PDF"""
    return f"""
    <html>
    <head><style>body{{font-family: Arial, sans-serif; padding: 20px;}} h1{{color: #2563eb;}} .summary{{background: #f8fafc; padding: 15px; border-radius: 8px;}}</style></head>
    <body>
        <h1>SME Tax Calculator - Official Report 2026</h1>
        <hr>
        <div class="summary">
            <h3>Financial Summary</h3>
            <p><strong>Total Revenue:</strong> {revenue:,.2f} EGP</p>
            <p><strong>Total Expenses:</strong> {expenses:,.2f} EGP</p>
            <p><strong>Net Profit:</strong> {(revenue - expenses):,.2f} EGP</p>
        </div>
        <h3>Tax Liability Assessment</h3>
        <ul>
            <li><strong>Law 152 (SMEs):</strong> {tax_152:,.2f} EGP</li>
            <li><strong>Law 91 (Income Tax):</strong> {tax_91:,.2f} EGP</li>
        </ul>
        <p><em>* This report is auto-generated by the SME Smart Tax Engine.</em></p>
    </body>
    </html>
    """

def add_transaction(current_df, category, trans_type, amount):
    new_record = {'Date': datetime.now().strftime("%Y-%m-%d %H:%M"), 'Category': category, 'Type': trans_type, 'Amount': amount}
    return pd.concat([current_df, pd.DataFrame([new_record])], ignore_index=True)

# ==========================================
# 2. Session State Initialization
# ==========================================
if 'logged_in' not in st.session_state: st.session_state.logged_in = False
if 'user_role' not in st.session_state: st.session_state.user_role = None
if 'data' not in st.session_state: st.session_state.data = pd.DataFrame(columns=['Date', 'Category', 'Type', 'Amount'])

# ==========================================
# 3. Application Interface
# ==========================================
if not st.session_state.logged_in:
    st.markdown("<h1 style='text-align:center;'>🔐 SME Tax Calculator Pro</h1>", unsafe_allow_html=True)
    _, col_login, _ = st.columns([1, 1.2, 1])
    with col_login:
        with st.form("login_form"):
            user_input = st.text_input("User ID")
            pass_input = st.text_input("Password", type="password")
            if st.form_submit_button("Access Dashboard"):
                is_valid, role = authenticate_user(user_input, pass_input)
                if is_valid:
                    st.session_state.logged_in, st.session_state.user_role = True, role
                    st.rerun()
                else:
                    st.error("Invalid credentials.")
else:
    # Sidebar
    if st.session_state.user_role == "premium":
        st.sidebar.markdown('<div class="premium-badge">💎 PREMIUM ACCOUNT</div>', unsafe_allow_html=True)
    
    menu = st.sidebar.radio("Navigation", ["🏠 Dashboard", "🛒 Add Sales", "💸 Add Expenses", "🧠 AI Tax Advisor (PRO)", "👥 Team"])
    if st.sidebar.button("Logout 🚪"):
        st.session_state.logged_in = False
        st.rerun()

    df = st.session_state.data
    total_rev = df[df['Type'] == 'Sale']['Amount'].sum() if not df.empty else 0.0
    total_exp = df[df['Type'] == 'Expense']['Amount'].sum() if not df.empty else 0.0
    t_152, t_91, profit = calculate_egyptian_taxes(total_rev, total_exp)

    # --- 1. Data Entry with Validation & Tooltips ---
    if menu == "🛒 Add Sales":
        st.title("🛒 Record Sales")
        with st.form("sale_form", clear_on_submit=True):
            c1, c2 = st.columns(2)
            cat = c1.text_input("Client/Invoice Detail", help="أدخل اسم العميل أو رقم الفاتورة لتسهيل المراجعة.")
            # Validation: min_value=0.0 prevents negative numbers
            amt = c2.number_input("Amount (EGP)", min_value=0.0, step=100.0, help="أدخل قيمة الفاتورة بالمصري. لا يمكن إدخال أرقام سالبة.")
            if st.form_submit_button("Save Record"):
                if amt > 0 and cat:
                    st.session_state.data = add_transaction(st.session_state.data, cat, "Sale", amt)
                    st.success("Transaction Saved!")
                else:
                    st.error("يرجى التأكد من إدخال وصف الفاتورة وقيمة أكبر من الصفر.")
        if not df[df['Type'] == 'Sale'].empty: st.dataframe(df[df['Type'] == 'Sale'])

    elif menu == "💸 Add Expenses":
        st.title("💸 Record Expenses")
        with st.form("exp_form", clear_on_submit=True):
            c1, c2 = st.columns(2)
            cat = c1.text_input("Expense Item", help="أدخل نوع المصروف (إيجار، مرتبات، بضاعة).")
            amt = c2.number_input("Amount (EGP)", min_value=0.0, step=100.0, help="يجب أن تكون المصروفات مدعمة بفواتير إلكترونية لخصمها ضريبياً.")
            if st.form_submit_button("Save Record"):
                if amt > 0 and cat:
                    st.session_state.data = add_transaction(st.session_state.data, cat, "Expense", amt)
                    st.success("Transaction Saved!")
                else:
                    st.error("بيانات غير مكتملة.")
        if not df[df['Type'] == 'Expense'].empty: st.dataframe(df[df['Type'] == 'Expense'])

    # --- 2. Smart AI Dashboard & Reporting ---
    elif menu == "🏠 Dashboard":
        st.title("📊 Financial Intelligence")
        m1, m2, m3, m4 = st.columns(4)
        m1.metric("Revenue", f"{total_rev:,.0f}")
        m2.metric("Expenses", f"{total_exp:,.0f}")
        m3.metric("Net Profit", f"{profit:,.0f}")
        m4.metric("Est. Tax", f"{min(t_152, t_91):,.0f}", delta_color="inverse")

        if not df.empty:
            fig = px.bar(df, x='Category', y='Amount', color='Type', barmode='group')
            st.plotly_chart(fig, use_container_width=True)

    elif menu == "🧠 AI Tax Advisor (PRO)":
        st.title("🧠 Smart Tax Optimizer")
        if st.session_state.user_role == "premium":
            st.subheader("🤖 AI Insights & Scenarios")
            advices = generate_tax_advice(total_rev, total_exp, t_152, t_91)
            for adv in advices:
                st.markdown(f'<div class="advice-box">{adv}</div>', unsafe_allow_html=True)
            
            st.markdown("---")
            st.subheader("📑 Generate Official Report")
            html_report = generate_html_report(total_rev, total_exp, t_152, t_91)
            # المستخدم ينزل التقرير بصيغة HTML ويقدر يطبعه PDF بسهولة (Ctrl+P)
            st.download_button(
                label="📥 Download Detailed Report (Ready for PDF Print)",
                data=html_report,
                file_name=f"Tax_Report_{datetime.now().strftime('%Y%m%d')}.html",
                mime="text/html"
            )
        else:
            st.error("🔒 Smart Advisor and Reports are PREMIUM features.")

    elif menu == "👥 Team":
        st.title("👥 Team")
        team_data = {"Name": ["Omar Mohamed", "Mennatallah Moamen", "Mareez Adham", "Basmala Mohamed", "Abdelrahman Ali", "Fares Salah", "Mohamed Hatem", "Youssef Sameh", "Apanob Gamil"],
                     "ID": ["2202297", "2200216", "2200243", "2200236", "2200190", "2202312", "2200137", "2200176", "2202995"]}
        st.table(pd.DataFrame(team_data))
